(() => {
  const cfg=window.JEBS_CONFIG||{}; const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.includes('YOUR-PROJECT')||!cfg.SUPABASE_ANON_KEY||cfg.SUPABASE_ANON_KEY.includes('YOUR-PUBLISHABLE')){$('#loginStatus').textContent='Configure config.js first.';return}
  const {createClient}=window.supabase, db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY); let user=null, profile=null, tab='dashboard';
  const nav=[['dashboard','⌂','Dashboard'],['settings','⚙','School Settings'],['hero','▣','Hero Slider'],['facilities','⌘','Facilities'],['teachers','◉','Teachers'],['students','♙','Students'],['gallery','▧','Gallery'],['achievements','★','Achievements'],['notices','!','Notices'],['events','◷','Calendar / Events'],['admissions','↓','Admission Inbox'],['messages','✉','Messages'],['security','🔐','Security']];
  $('#nav').innerHTML=nav.map(x=>`<button data-tab="${x[0]}">${x[1]} <span>${x[2]}</span></button>`).join('');
  $('#loginForm').addEventListener('submit',login); $('#logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload()}); $('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b){tab=b.dataset.tab;render()}});
  $('#content').addEventListener('submit',async e=>{const f=e.target.closest('.record-form');if(f){e.preventDefault();try{await saveRecord(f)}catch(x){alert(x.message)}}});
  $('#content').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(b)removeRecord(b.dataset.table,b.dataset.id); const edit=e.target.closest('[data-edit]');if(edit){const form=edit.closest('.panel')?.nextElementSibling;if(form)form.classList.toggle('hidden')}});
  db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){location.reload()} if(session&& !user){init(session)}});
  init();
  async function init(session){const {data:{session:s}}=await db.auth.getSession(); const ses=session||s;if(!ses){$('#login').hidden=false;$('#dashboard').hidden=true;return} user=ses.user; const r=await db.from('profiles').select('*').eq('id',user.id).maybeSingle(); if(r.error||!r.data||!['admin','staff'].includes(r.data.role)){await db.auth.signOut();$('#loginStatus').textContent='This account is not authorized for JEBS Admin.';return} profile=r.data; $('#login').hidden=true;$('#dashboard').hidden=false;$('#userPill').textContent=`${profile.full_name||user.email} · ${profile.role}`;render();}
  async function login(e){e.preventDefault();$('#loginStatus').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});$('#loginStatus').textContent=error?error.message:'Success…';if(error)return; await init();}
  function render(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const title=nav.find(x=>x[0]===tab)?.[2]||'Dashboard';$('#pageTitle').textContent=title;$('#content').innerHTML=views[tab]();bindView();}
  const views={
    dashboard:()=>`<div class="grid4"><div class="stat"><strong id="countTeachers">—</strong><span>Teacher profiles</span></div><div class="stat"><strong id="countStudents">—</strong><span>Private student records</span></div><div class="stat"><strong id="countAdmissions">—</strong><span>Admission enquiries</span></div><div class="stat"><strong id="countMessages">—</strong><span>Inbox messages</span></div></div><div class="panel" style="margin-top:18px"><h2>Welcome to the JEBS control room</h2><p class="muted">This production version uses Supabase Authentication, PostgreSQL Row Level Security and separate public/private storage buckets. Public visitors cannot read student records or the private inbox.</p><div class="successbox">Security rule: never paste a Supabase <b>service_role</b> key into this website. Only the publishable/anon key belongs in <code>config.js</code>.</div></div><div class="panel"><h3>Quick actions</h3><div class="actions"><button class="primary" data-go="hero">Update Hero Slides</button><button class="secondary" data-go="gallery">Upload Gallery</button><button class="secondary" data-go="teachers">Manage Teachers</button><button class="secondary" data-go="notices">Publish Notice</button><button class="secondary" data-go="admissions">Open Admissions</button></div></div>`,
    settings:()=>`<div class="panel"><h2>School identity & communication</h2><form id="settingsForm" class="formgrid"><div class="field"><label>School name<input name="school_name" id="school_name"></label></div><div class="field"><label>Logo URL<input name="logo_url" id="logo_url" placeholder="https://..."></label></div><div class="field wide"><label>Address<input name="address" id="address"></label></div><div class="field"><label>Phone<input name="phone" id="phone"></label></div><div class="field"><label>Landline<input name="landline" id="landline"></label></div><div class="field"><label>Email<input name="email" type="email" id="email"></label></div><div class="field"><label>Admission receiver phone<input name="admission_phone" id="admission_phone"></label></div><div class="field wide"><label>Tagline<input name="tagline" id="tagline"></label></div>${['facebook','youtube','instagram','tiktok','twitter','messenger'].map(k=>`<div class="field"><label>${k==='youtube'?'YouTube Channel':k==='facebook'?'Facebook Page':k[0].toUpperCase()+k.slice(1)} URL<input name="${k}" id="${k}" placeholder="https://..."></label></div>`).join('')}<div class="field wide"><label>Google Maps Embed URL<input name="map_embed_url" id="map_embed_url" placeholder="Paste the src URL from Google Maps embed code, not the whole iframe"></label></div><div class="toolbar wide"><button class="primary">Save Settings</button></div></form></div><div class="panel"><h3>How to set Google Maps</h3><p class="muted">Google Maps → Share → Embed a map → copy the URL inside the iframe's <code>src="..."</code> → paste it above. The public website will display the map.</p></div>`,
    hero:()=>listView('Hero Slider','hero_slides',heroForm), facilities:()=>listView('Facilities','facilities',facilityForm), teachers:()=>listView('Teachers','teachers',teacherForm), students:()=>listView('Private Student Records','students',studentForm,true), gallery:()=>listView('Gallery','gallery',galleryForm), achievements:()=>listView('Achievements','achievements',achievementForm), notices:()=>listView('Notices','notices',noticeForm), events:()=>listView('Calendar / Events','events',eventForm),
    admissions:()=>inbox('Admission Inbox','admissions',['student_name','parent_name','applying_class','phone','email','address','message','status','created_at']),
    messages:()=>inbox('Contact Messages','contact_messages',['name','email','phone','message','status','created_at']),
    security:()=>`<div class="panel"><h2>Account security</h2><p class="muted">Your Admin ID is the signed-in email address. Change your password regularly and never share it. Use a unique password that you do not reuse elsewhere.</p><form id="securityForm" class="formgrid"><div class="field"><label>New password<input id="newPassword" type="password" minlength="12" required placeholder="At least 12 characters"></label></div><div class="field"><label>Confirm new password<input id="confirmPassword" type="password" minlength="12" required></label></div><div class="toolbar wide"><button class="primary">Change Password</button></div></form><div id="securityStatus"></div></div><div class="panel"><h3>Production security checklist</h3><ul class="muted"><li>RLS enabled on every table.</li><li>Student records are private.</li><li>Private student images use a non-public bucket.</li><li>Only published public content is readable anonymously.</li><li>Admin authorization is checked against the profiles table.</li><li>Service-role credentials are never shipped to the browser.</li></ul></div>`
  };
  function listView(title,table,form,privateTable=false){return `<div class="panel"><div class="row between"><div><h2>${title}</h2><p class="muted">${privateTable?'Private staff-only records. Do not publish personal data unnecessarily.':'Changes are published according to the Published switch.'}</p></div><button class="primary" data-add="${table}">+ Add New</button></div><div id="list-${table}"><p class="muted">Loading…</p></div></div>`}
  function formShell(table,id,body,extra=''){return `<form class="editor record-form" data-table="${table}" data-id="${id||''}">${body}<div class="actions"><button class="primary" type="submit">Save</button>${id?`<button type="button" class="danger" data-delete="${table}" data-id="${id}">Delete</button>`:''}${extra}</div></form>`}
  function pubFields(row){return `<label class="switch"><input type="checkbox" name="published" ${row?.published!==false?'checked':''}> Published on public website</label>`}
  function fileField(label,name,existing,privateBucket=false){return `<div class="field"><label>${label}<input type="file" name="${name}" accept="image/jpeg,image/png,image/webp,image/svg+xml" data-image-input="${privateBucket?'private':'public'}"><small class="muted">JPG/PNG/WebP/SVG · max 5 MB</small></label>${existing?`<img class="preview" src="${esc(existing)}" alt="Preview">`:''}</div>`}
  function heroForm(r={}){return formShell('hero_slides',r.id,`<div class="editor-grid">${fileField('Slide image','image_file',r.image_url)}<div class="formgrid"><div class="field"><label>Title<input name="title" maxlength="100" value="${esc(r.title)}" required></label></div><div class="field"><label>Subtitle<input name="subtitle" maxlength="100" value="${esc(r.subtitle)}"></label></div><div class="field wide"><label>Description<textarea name="description" maxlength="500">${esc(r.description)}</textarea></label></div><div class="field"><label>Order<input name="sort_order" type="number" value="${r.sort_order||0}"></label></div><div class="field">${pubFields(r)}</div></div></div>`)}
  function facilityForm(r={}){return formShell('facilities',r.id,`<div class="editor-grid">${fileField('Facility photo','image_file',r.image_url)}<div class="formgrid"><div class="field"><label>Title<input name="title" maxlength="100" value="${esc(r.title)}" required></label></div><div class="field"><label>Order<input name="sort_order" type="number" value="${r.sort_order||0}"></label></div><div class="field wide"><label>Short description<input name="short_description" maxlength="220" value="${esc(r.short_description)}"></label></div><div class="field wide"><label>Full details<textarea name="details" maxlength="1200">${esc(r.details)}</textarea></label></div><div class="field wide">${pubFields(r)}</div></div></div>`)}
  function teacherForm(r={}){return formShell('teachers',r.id,`<div class="editor-grid">${fileField('Teacher photo','image_file',r.image_url)}<div class="formgrid"><div class="field"><label>Name<input name="name" maxlength="100" value="${esc(r.name)}" required></label></div><div class="field"><label>Position<input name="position" maxlength="100" value="${esc(r.position)}"></label></div><div class="field"><label>Subject<input name="subject" maxlength="100" value="${esc(r.subject)}"></label></div><div class="field"><label>Phone<input name="phone" maxlength="25" value="${esc(r.phone)}"></label></div><div class="field"><label>Email<input name="email" maxlength="160" value="${esc(r.email)}"></label></div><div class="field"><label>Order<input name="sort_order" type="number" value="${r.sort_order||0}"></label></div><div class="field wide"><label>Short bio<textarea name="bio" maxlength="700">${esc(r.bio)}</textarea></label></div><div class="field wide">${pubFields(r)}</div></div></div>`)}
  function studentForm(r={}){return formShell('students',r.id,`<div class="editor-grid">${fileField('Private student photo','image_file',null,true)}<div class="formgrid"><div class="field"><label>Student name<input name="name" maxlength="100" value="${esc(r.name)}" required></label></div><div class="field"><label>Class<input name="class_name" maxlength="30" value="${esc(r.class_name)}"></label></div><div class="field wide"><label>Address<input name="address" maxlength="300" value="${esc(r.address)}"></label></div><div class="field"><label>Parent / Guardian<input name="parent_name" maxlength="100" value="${esc(r.parent_name)}"></label></div><div class="field"><label>Parent phone<input name="parent_phone" maxlength="25" value="${esc(r.parent_phone)}"></label></div><div class="field wide"><label>Private notes<textarea name="notes" maxlength="1000">${esc(r.notes)}</textarea></label></div></div></div><div class="dangerbox">Student records are never shown on the public website. Keep only the data the school actually needs.</div>`)}
  function galleryForm(r={}){return formShell('gallery',r.id,`<div class="editor-grid">${fileField('Gallery image','image_file',r.image_url)}<div class="formgrid"><div class="field"><label>Caption<input name="title" maxlength="150" value="${esc(r.title)}"></label></div><div class="field"><label>Order<input name="sort_order" type="number" value="${r.sort_order||0}"></label></div><div class="field wide">${pubFields(r)}</div></div></div>`)}
  function achievementForm(r={}){return formShell('achievements',r.id,`<div class="editor-grid">${fileField('Achievement photo','image_file',r.image_url)}<div class="formgrid"><div class="field"><label>Title<input name="title" maxlength="150" value="${esc(r.title)}" required></label></div><div class="field"><label>Date<input name="date_text" maxlength="60" value="${esc(r.date_text)}"></label></div><div class="field wide"><label>Description<textarea name="body" maxlength="1200">${esc(r.body)}</textarea></label></div><div class="field wide">${pubFields(r)}</div></div></div>`)}
  function noticeForm(r={}){return formShell('notices',r.id,`<div class="formgrid"><div class="field"><label>Title<input name="title" maxlength="150" value="${esc(r.title)}" required></label></div><div class="field"><label>Date / Nepali date<input name="date_text" maxlength="60" value="${esc(r.date_text)}"></label></div><div class="field wide"><label>Notice<textarea name="body" maxlength="2000">${esc(r.body)}</textarea></label></div><div class="field wide">${pubFields(r)}</div></div>`)}
  function eventForm(r={}){return formShell('events',r.id,`<div class="formgrid"><div class="field"><label>Event title<input name="title" maxlength="150" value="${esc(r.title)}" required></label></div><div class="field"><label>Date<input name="event_date" type="date" value="${esc(r.event_date)}"></label></div><div class="field wide"><label>Description<textarea name="description" maxlength="800">${esc(r.description)}</textarea></label></div><div class="field wide">${pubFields(r)}</div></div>`)}
  const tableConfig={hero_slides:{select:'*',order:['sort_order'],form:heroForm},facilities:{select:'*',order:['sort_order'],form:facilityForm},teachers:{select:'*',order:['sort_order'],form:teacherForm},students:{select:'*',order:['created_at'],form:studentForm},gallery:{select:'*',order:['sort_order'],form:galleryForm},achievements:{select:'*',order:['sort_order'],form:achievementForm},notices:{select:'*',order:['created_at'],form:noticeForm},events:{select:'*',order:['event_date'],form:eventForm}};
  async function loadList(table){const cfgx=tableConfig[table];let q=db.from(table).select(cfgx.select);const order=cfgx.order[0];q=q.order(order,{ascending:order==='sort_order'||order==='event_date'});const {data,error}=await q;if(error){$('#list-'+table).innerHTML=`<div class="dangerbox">${esc(error.message)}</div>`;return}$('#list-'+table).innerHTML=data.length?data.map(r=>`<div class="panel" style="margin:10px 0;padding:12px"><div class="row between"><div><b>${esc(r.title||r.name||'Record')}</b><div class="muted">${esc(r.position||r.class_name||r.date_text||r.event_date||'')}</div></div><button class="secondary" data-edit="${table}" data-id="${r.id}">Edit</button></div></div>${cfgx.form(r)}`).join(''): '<div class="muted">No records yet. Click Add New.</div>'; $('#list-'+table).querySelectorAll('.record-form').forEach(f=>f.classList.add('hidden'));}
  async function loadInbox(table,fields){const {data,error}=await db.from(table).select('*').order('created_at',{ascending:false});const el=$('#content .inboxlist');if(error){el.innerHTML=`<div class="dangerbox">${esc(error.message)}</div>`;return}const statuses=table==='admissions'?['new','contacted','reviewing','accepted','closed']:['new','read','replied','closed']; el.innerHTML=data.length?data.map(r=>`<article class="notice"><div><span class="status">${esc(r.status)}</span> <small>${new Date(r.created_at).toLocaleString()}</small></div><div>${fields.filter(k=>!['status','created_at'].includes(k)).map(k=>`<p><b>${esc(k.replaceAll('_',' '))}:</b> ${esc(r[k]||'—')}</p>`).join('')}<div class="actions"><select data-status-table="${table}" data-id="${r.id}">${statuses.map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select>${r.phone?`<a class="secondary" href="tel:${esc(r.phone.replace(/[^\d+]/g,''))}">Call</a>`:''}${r.email?`<a class="secondary" href="mailto:${esc(r.email)}">Email</a>`:''}</div></div></article>`).join(''):'<div class="muted">Inbox is empty.</div>';}
  function inbox(title,table,fields){return `<div class="panel"><h2>${title}</h2><p class="muted">Only authorized staff/admin users can read these records.</p><div class="inboxlist"><p class="muted">Loading…</p></div></div>`}
  async function saveRecord(form){const table=form.dataset.table,id=form.dataset.id||null;const fd=new FormData(form);const file=fd.get('image_file');fd.delete('image_file');const payload={};for(const [k,v] of fd.entries()){if(k==='published')payload[k]=true;else if(k==='sort_order')payload[k]=Number(v||0);else payload[k]=v;}if('published' in payload===false && ['hero_slides','facilities','teachers','gallery','achievements','notices','events'].includes(table))payload.published=false;if(table==='students'&&file&&file.size)payload.image_path=await upload(file,'student-private',`students/${crypto.randomUUID()}`);else if(file&&file.size)payload.image_url=await upload(file,'school-public',`${table}/${crypto.randomUUID()}`);let res=id?await db.from(table).update(payload).eq('id',id):await db.from(table).insert(payload);if(res.error)throw res.error;await loadList(table);alert('Saved successfully.');}
  async function upload(file,bucket,path){if(file.size>5*1024*1024)throw new Error('Image is larger than 5 MB.');if(!/^image\/(jpeg|png|webp|svg\+xml)$/.test(file.type))throw new Error('Only JPG, PNG, WebP or SVG images are allowed.');const {error}=await db.storage.from(bucket).upload(path,file,{upsert:false,cacheControl:'31536000'});if(error)throw error;if(bucket==='school-public')return db.storage.from(bucket).getPublicUrl(path).data.publicUrl;return path;}
  async function removeRecord(table,id){if(!confirm('Delete this record?'))return;const {error}=await db.from(table).delete().eq('id',id);if(error)alert(error.message);else await loadList(table);}
  async function saveSettings(){const f=$('#settingsForm'),fd=new FormData(f),payload=Object.fromEntries(fd.entries());const {error}=await db.from('site_settings').upsert({id:true,...payload},{onConflict:'id'});$('#content').insertAdjacentHTML('afterbegin',error?`<div class="dangerbox">${esc(error.message)}</div>`:'<div class="successbox">Settings saved.</div>');}
  async function bindView(){
    document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;render()});
    if(tab==='dashboard')loadCounts();
    if(tab==='settings')loadSettings();
    if(tableConfig[tab]){await loadList(tab);document.querySelectorAll(`[data-add="${tab}"]`).forEach(b=>b.onclick=()=>{const host=$(`#list-${tab}`);host.insertAdjacentHTML('afterbegin',tableConfig[tab].form({}));});}
    if(tab==='admissions')loadInbox('admissions',['student_name','parent_name','current_class','applying_class','phone','email','address','message','status','created_at']);
    if(tab==='messages')loadInbox('contact_messages',['name','email','phone','message','status','created_at']);
    $('#settingsForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await saveSettings()}catch(x){alert(x.message)}});
    $('#securityForm')?.addEventListener('submit',changePassword);
    document.querySelectorAll('[data-status-table]').forEach(s=>s.onchange=async()=>{const table=s.dataset.statusTable,id=s.dataset.id,status=s.value;const {error}=await db.from(table).update({status}).eq('id',id);if(error)alert(error.message)});
  }
  async function loadCounts(){const pairs=await Promise.all(['teachers','students','admissions','contact_messages'].map(t=>db.from(t).select('*',{count:'exact',head:true})));['countTeachers','countStudents','countAdmissions','countMessages'].forEach((id,i)=>$( '#'+id).textContent=pairs[i].count??'0');}
  async function loadSettings(){const {data,error}=await db.from('site_settings').select('*').eq('id',true).maybeSingle();if(error)return alert(error.message);if(!data)return;for(const [k,v] of Object.entries(data)){const el=$('#'+k);if(el)el.value=v||''}}
  async function changePassword(e){e.preventDefault();const a=$('#newPassword').value,b=$('#confirmPassword').value;if(a.length<12)return $('#securityStatus').innerHTML='<div class="dangerbox">Use at least 12 characters.</div>';if(a!==b)return $('#securityStatus').innerHTML='<div class="dangerbox">Passwords do not match.</div>';const {error}=await db.auth.updateUser({password:a});$('#securityStatus').innerHTML=error?`<div class="dangerbox">${esc(error.message)}</div>`:'<div class="successbox">Password changed successfully. Keep it private.</div>';if(!error)e.target.reset()}
})();
