/* JEBS Production Public Website
   Security note: this client uses only Supabase's publishable/anon key.
   Database RLS controls what anonymous visitors can read/write. Never put service_role here.
*/
(() => {
  const cfg = window.JEBS_CONFIG || {};
  const app = document.getElementById('app');
  const loading = document.getElementById('loading');
  if (!cfg.SUPABASE_URL || cfg.SUPABASE_URL.includes('YOUR-PROJECT') || !cfg.SUPABASE_ANON_KEY || cfg.SUPABASE_ANON_KEY.includes('YOUR-PUBLISHABLE')) {
    loading.innerHTML = '<div class="setup-card"><b>JEBS website is ready.</b><p>Open <code>config.js</code> and add the Supabase project URL and publishable key, then refresh.</p></div>';
    return;
  }
  const { createClient } = window.supabase;
  const db = createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, { auth: { persistSession: false } });
  const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const url = (v='') => /^https?:\/\//i.test(v) ? v : '#';
  const tel = (v='') => String(v).replace(/[^\d+]/g,'');
  let state = { settings:{}, hero:[], facilities:[], teachers:[], gallery:[], achievements:[], notices:[], events:[] };
  const q = s => document.querySelector(s);

  async function load(){
    const queries = await Promise.all([
      db.from('site_settings').select('*').eq('id', true).maybeSingle(),
      db.from('hero_slides').select('*').eq('published', true).order('sort_order'),
      db.from('facilities').select('*').eq('published', true).order('sort_order'),
      db.from('teachers').select('*').eq('published', true).order('sort_order').limit(30),
      db.from('gallery').select('*').eq('published', true).order('sort_order').limit(60),
      db.from('achievements').select('*').eq('published', true).order('sort_order').limit(12),
      db.from('notices').select('*').eq('published', true).order('created_at',{ascending:false}).limit(8),
      db.from('events').select('*').eq('published', true).order('event_date').limit(8)
    ]);
    const bad = queries.find(x => x.error);
    if (bad) throw bad.error;
    [state.settings,state.hero,state.facilities,state.teachers,state.gallery,state.achievements,state.notices,state.events] = queries.map(x => x.data);
    render();
  }
  function render(){
    const s=state.settings||{};
    const logo=s.logo_url || 'assets/school-logo.svg';
    app.innerHTML=`
      <div class="topbar"><div>📍 ${esc(s.address||'Krishnapur-5, Kanchanpur, Nepal')}</div><div class="topcontact"><a href="tel:${esc(tel(s.phone))}">☎ ${esc(s.phone||'School Phone')}</a><span>·</span><a href="mailto:${esc(s.email||'')}">✉ ${esc(s.email||'School Email')}</a></div></div>
      <header class="nav"><a class="brand" href="#home"><img src="${esc(logo)}" alt="School logo"><span><b>${esc(s.school_name||'JYOTI ENGLISH')}</b><strong>BOARDING SCHOOL</strong><small>Krishnapur-5, Kanchanpur</small></span></a><button class="menu" aria-label="Menu">☰</button><nav id="navlinks"><a href="#about">About</a><a href="#academics">Academics</a><a href="#facilities">Facilities</a><a href="#teachers">Teachers</a><a href="#gallery">Gallery</a><a href="#notices">Notice</a><a href="#contact">Contact</a><a class="admit" href="#admission">Admission</a></nav></header>
      <main>
      <section id="home" class="hero"><div class="hero-slides">${(state.hero.length?state.hero:[{title:'JYOTI ENGLISH',subtitle:'BOARDING SCHOOL',description:s.tagline||'Nurturing Minds. Building Character. Creating Leaders.'}]).map((h,i)=>`<article class="hero-slide ${i===0?'active':''}" style="${h.image_url?`background-image:linear-gradient(90deg,rgba(3,28,63,.92),rgba(3,28,63,.20)),url('${esc(h.image_url)}')`:''}"><div class="hero-copy"><span>ESTABLISHED 2049 B.S. • JEBS</span><h1>${esc(h.title)}<em>${esc(h.subtitle||'')}</em></h1><p>${esc(h.description||'')}</p><div><a class="btn gold" href="#about">Explore School →</a><a class="btn glass" href="#admission">Admission</a></div></div></article>`).join('')}</div>${state.hero.length>1?'<button class="hero-prev" aria-label="Previous">‹</button><button class="hero-next" aria-label="Next">›</button><div class="hero-dots">'+state.hero.map((_,i)=>`<button data-slide="${i}" class="${i===0?'active':''}" aria-label="Slide ${i+1}"></button>`).join('')+'</div>':''}</section>
      <section class="ticker"><b>📢 LATEST NOTICE</b><span>${esc(state.notices[0]?.title||'School notices and updates')}</span><a href="#notices">View all →</a></section>
      <section id="about" class="section"><div class="eyebrow">ABOUT OUR SCHOOL</div><h2>Excellence in education, <em>character in action.</em></h2><div class="about-grid"><div><p>Jyoti English Boarding School is committed to providing quality education in a safe, disciplined and friendly environment. We aim to develop knowledgeable, responsible and compassionate citizens.</p><p>Founded in 2049 B.S., JEBS continues to support students through academic learning, practical activities, sports, creativity and leadership.</p><a class="text-link" href="#contact">Connect with School →</a></div><div class="stat-box"><img src="${esc(logo)}" alt="JEBS logo"><div><strong>2049 B.S.</strong><span>Established</span></div><div><strong>${state.teachers.length||'—'}+</strong><span>Public teacher profiles</span></div><div><strong>10+</strong><span>Learning levels</span></div></div></div></section>
      <section id="academics" class="section soft"><div class="eyebrow">ACADEMICS</div><h2>Learning that builds a <em>strong future.</em></h2><div class="card-grid">${[['🎓','Quality Education','Student-centered learning, clear academic goals and supportive teaching.'],['📚','Holistic Development','Academic, social, physical, creative and moral development.'],['💡','Modern Learning','Practical activities, technology and resources that make learning meaningful.'],['🌟','Bright Future','Confidence, discipline, leadership and lifelong learning habits.']].map((x,i)=>`<a class="info-card" href="#academic-${i}"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><span>Learn more →</span></a>`).join('')}</div><div class="detail-grid">${[['Quality Education','Experienced teachers, student-focused instruction, regular assessment and a caring classroom environment.'],['Holistic Development','Opportunities for sports, creativity, teamwork, communication, discipline and responsible citizenship.'],['Modern Learning','Technology-supported lessons, practical activities and resources that connect classroom learning with real life.'],['Bright Future','Leadership, confidence, communication skills and habits that prepare students for further study and life.']].map((x,i)=>`<article id="academic-${i}"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section>
      <section id="facilities" class="section"><div class="eyebrow">OUR FACILITIES</div><h2>Spaces designed for <em>better learning.</em></h2><div class="facility-grid">${state.facilities.map((f,i)=>`<article class="facility"><img src="${esc(f.image_url||'assets/facility-placeholder.svg')}" alt="${esc(f.title)}"><div><span>0${i+1}</span><h3>${esc(f.title)}</h3><p>${esc(f.short_description||'')}</p><details><summary>View details</summary><p>${esc(f.details||'')}</p></details></div></article>`).join('')}</div></section>
      <section id="teachers" class="section soft"><div class="eyebrow">OUR PEOPLE</div><h2>Experienced <em>teachers.</em></h2><div class="people-grid">${state.teachers.map(t=>`<article class="person"><img src="${esc(t.image_url||logo)}" alt="${esc(t.name)}"><div><span>${esc(t.position||'Teacher')}</span><h3>${esc(t.name)}</h3><b>${esc(t.subject||'')}</b><p>${esc(t.bio||'')}</p><div class="person-links">${t.phone?`<a href="tel:${esc(tel(t.phone))}">Call</a>`:''}${t.email?`<a href="mailto:${esc(t.email)}">Email</a>`:''}</div></div></article>`).join('')||'<div class="empty">Teacher profiles will appear here.</div>'}</div></section>
      <section id="achievements" class="section"><div class="eyebrow">ACHIEVEMENTS</div><h2>Celebrating <em>student success.</em></h2><div class="achievement-grid">${state.achievements.map(a=>`<article><img src="${esc(a.image_url||logo)}" alt="${esc(a.title)}"><div><small>${esc(a.date_text||'')}</small><h3>${esc(a.title)}</h3><p>${esc(a.body||'')}</p></div></article>`).join('')||'<div class="empty">Achievements will appear here.</div>'}</div></section>
      <section id="gallery" class="section soft"><div class="eyebrow">PHOTO GALLERY</div><h2>Life at <em>JEBS.</em></h2><div class="gallery-grid">${state.gallery.map(g=>`<figure><img loading="lazy" src="${esc(g.image_url)}" alt="${esc(g.title||'School gallery photo')}"><figcaption>${esc(g.title||'JEBS')}</figcaption></figure>`).join('')||'<div class="empty">Gallery photos will appear here.</div>'}</div></section>
      <section id="admission" class="section admission-section"><div><div class="eyebrow">ADMISSION ENQUIRY</div><h2>Start your child's journey with <em>JEBS.</em></h2><p>Submit the form. Your enquiry goes securely to the school's private Admin Inbox.</p><ul><li>Nursery, LKG, UKG and Grade 1–10</li><li>Phone required; email optional</li><li>Admin can review and update enquiry status</li></ul></div><form id="admissionForm" class="form-card"><input name="website" tabindex="-1" autocomplete="off" class="hp" aria-hidden="true"><label>Student Name<input name="student_name" maxlength="100" required></label><label>Parent / Guardian<input name="parent_name" maxlength="100" required></label><div class="two"><label>Current Class<select name="current_class"><option>New Student</option><option>Nursery</option><option>LKG</option><option>UKG</option><option>Grade 1</option><option>Grade 2</option><option>Grade 3</option><option>Grade 4</option><option>Grade 5</option><option>Grade 6</option><option>Grade 7</option><option>Grade 8</option><option>Grade 9</option><option>Grade 10</option></select></label><label>Applying Class<select name="applying_class" required><option value="">Select</option><option>Nursery</option><option>LKG</option><option>UKG</option><option>Grade 1</option><option>Grade 2</option><option>Grade 3</option><option>Grade 4</option><option>Grade 5</option><option>Grade 6</option><option>Grade 7</option><option>Grade 8</option><option>Grade 9</option><option>Grade 10</option></select></label></div><div class="two"><label>Phone<input name="phone" type="tel" maxlength="25" required></label><label>Email (optional)<input name="email" type="email" maxlength="160"></label></div><label>Address<textarea name="address" maxlength="500"></textarea></label><label>Message<textarea name="message" maxlength="1000"></textarea></label><button class="btn gold" type="submit">Send Secure Enquiry →</button><div id="admissionStatus" class="form-status"></div></form></section>
      <section id="notices" class="section"><div class="eyebrow">NOTICE & CALENDAR</div><h2>Stay <em>updated.</em></h2><div class="notice-grid"><div>${state.notices.map(n=>`<article class="notice"><time>${esc(n.date_text||'')}</time><div><h3>${esc(n.title)}</h3><p>${esc(n.body||'')}</p></div></article>`).join('')||'<div class="empty">No published notices.</div>'}</div><aside><h3>Upcoming Events</h3>${state.events.map(e=>`<div class="event"><b>${e.event_date?new Date(e.event_date+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short'}):'—'}</b><span><strong>${esc(e.title)}</strong>${esc(e.description||'')}</span></div>`).join('')||'<p>No upcoming events.</p>'}</aside></div></section>
      <section id="contact" class="section contact"><div><div class="eyebrow">CONTACT JEBS</div><h2>We are here to <em>help.</em></h2><p>${esc(s.address||'')}</p><p>${s.phone?`<a href="tel:${esc(tel(s.phone))}">${esc(s.phone)}</a>`:''}${s.landline?` · <a href="tel:${esc(tel(s.landline))}">${esc(s.landline)}</a>`:''}</p><p>${s.email?`<a href="mailto:${esc(s.email)}">${esc(s.email)}</a>`:''}</p><div class="social">${socialLink(s.facebook,'Facebook','f')}${socialLink(s.youtube,'YouTube','▶')}${socialLink(s.instagram,'Instagram','◎')}${socialLink(s.tiktok,'TikTok','♪')}${socialLink(s.twitter,'X','𝕏')}${socialLink(s.messenger,'Messenger','M')}</div><form id="contactForm" class="contact-form"><input name="website" tabindex="-1" class="hp"><input name="name" placeholder="Your name" maxlength="100" required><input name="email" type="email" placeholder="Email (optional)" maxlength="160"><input name="phone" placeholder="Phone" maxlength="25"><textarea name="message" placeholder="Your message" maxlength="1000" required></textarea><button class="btn navy">Send Message</button><div id="contactStatus" class="form-status"></div></form></div><div class="map-wrap">${s.map_embed_url?`<iframe loading="lazy" src="${esc(s.map_embed_url)}" referrerpolicy="no-referrer-when-downgrade" allowfullscreen title="JEBS location map"></iframe>`:'<div class="map-empty">Google Maps location will be configured by Admin.</div>'}</div></section>
      </main><footer><div class="footer-brand"><img src="${esc(logo)}"><div><b>${esc(s.school_name||'Jyoti English Boarding School')}</b><span>${esc(s.tagline||'Nurturing Minds. Building Character. Creating Leaders.')}</span></div></div><div class="footer-links"><a href="#about">About</a><a href="#facilities">Facilities</a><a href="#teachers">Teachers</a><a href="#gallery">Gallery</a><a href="#notices">Notice</a><a href="admin.html">Admin Login</a></div><div class="copy">© ${new Date().getFullYear()} ${esc(s.school_name||'JEBS')}. All Rights Reserved.</div></footer>`;
    bind();
    loading.remove(); app.hidden=false;
  }
  function socialLink(v,label,icon){return v&&url(v)?`<a href="${esc(v)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(label)}">${icon}</a>`:''}
  function bind(){
    q('.menu')?.addEventListener('click',()=>q('#navlinks').classList.toggle('open'));
    const slides=[...document.querySelectorAll('.hero-slide')], dots=[...document.querySelectorAll('.hero-dots button')]; let cur=0;
    const show=i=>{if(!slides.length)return;cur=(i+slides.length)%slides.length;slides.forEach((x,n)=>x.classList.toggle('active',n===cur));dots.forEach((x,n)=>x.classList.toggle('active',n===cur));};
    q('.hero-prev')?.addEventListener('click',()=>show(cur-1)); q('.hero-next')?.addEventListener('click',()=>show(cur+1)); dots.forEach(d=>d.addEventListener('click',()=>show(Number(d.dataset.slide))));
    if(slides.length>1)setInterval(()=>show(cur+1),6500);
    document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>q('#navlinks')?.classList.remove('open')));
    q('#admissionForm')?.addEventListener('submit', submitAdmission); q('#contactForm')?.addEventListener('submit', submitContact);
  }
  async function submitAdmission(e){e.preventDefault(); const f=e.currentTarget, status=q('#admissionStatus'); if(f.website.value)return; status.textContent='Sending…'; const fd=new FormData(f); const payload=Object.fromEntries(fd.entries()); delete payload.website; const {error}=await db.from('admissions').insert(payload); status.textContent=error?'Please try again or call the school.':'Thank you. Your admission enquiry has been received.'; if(!error)f.reset();}
  async function submitContact(e){e.preventDefault(); const f=e.currentTarget,status=q('#contactStatus'); if(f.website.value)return; status.textContent='Sending…'; const fd=new FormData(f); const payload=Object.fromEntries(fd.entries()); delete payload.website; const {error}=await db.from('contact_messages').insert(payload); status.textContent=error?'Please try again.':'Message sent successfully.'; if(!error)f.reset();}
  load().catch(err=>{console.error(err);loading.innerHTML='<div class="setup-card"><b>JEBS is temporarily unavailable.</b><p>Please check the Supabase setup and database policies, then refresh.</p></div>';});
})();
